// Generated by CoffeeScript 1.12.7
(function() {
  var Carros, Cinema, Futebol, Hobbie, Musica, Outros, Videogame, botao, captura_nome, captura_profissoes, captura_religiao, capturar_idade, define_tipo_de_hobbie, gerar_idade, gerar_nome, gerar_profissoes, gerar_religiao, gerar_texto, gerar_texto_de_itens,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Hobbie = (function() {
    function Hobbie() {}

    Hobbie.prototype.define_taxa_de_gosto = function() {
      this.valor = [];
      this.valor.push(this.taxa_de_gosto.indexOf("Um"));
      this.valor.push(this.taxa_de_gosto.indexOf("Mais"));
      this.valor.push(this.taxa_de_gosto.indexOf("Muito"));
      return this.taxa_de_gosto = this.valor.indexOf(0);
    };

    Hobbie.prototype.captura_elementos_escolhidos = function() {
      var i, j, ref, results, x;
      this.elementos_escolhidos = [];
      x = this.id.length;
      --x;
      results = [];
      for (i = j = 0, ref = x; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        if (document.getElementById(this.id[i]).checked) {
          results.push(this.elementos_escolhidos.push(this.id[i]));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return Hobbie;

  })();

  Cinema = (function(superClass) {
    extend(Cinema, superClass);

    function Cinema(tipo) {
      this.taxa_de_gosto = document.getElementById("cinema_taxa_de_gosto").selectedOptions[0].textContent;
      this.id = ["comedia", "romance", "ficao", "acao", "aventura", "documentarios"];
      this.define_taxa_de_gosto();
      this.captura_elementos_escolhidos();
    }

    Cinema.prototype.converte_id_em_textos = function() {
      return this.elementos_convertidos = this.elementos_escolhidos.map(function(x) {
        console.log(x);
        x = x.replace("comedia", "comédia");
        x = x.replace("ficao", "ficção científica");
        x = x.replace("acao", "ação");
        return x = x.replace("documentarios", "documentários");
      });
    };

    Cinema.prototype.defini_texto = function() {
      var texto;
      switch (this.taxa_de_gosto) {
        case 0:
          texto = "curto um pouco de filmes";
          break;
        case 1:
          texto = "gosto de filmes";
          break;
        case 2:
          texto = "sou apaixonado por cinema";
      }
      if (this.elementos_escolhidos !== 0) {
        this.converte_id_em_textos();
        return texto = texto + ", especialmente de " + gerar_texto_de_itens(this.elementos_convertidos) + "";
      }
    };

    return Cinema;

  })(Hobbie);

  Musica = (function(superClass) {
    extend(Musica, superClass);

    function Musica() {
      this.taxa_de_gosto = document.getElementById("musica_taxa_de_gosto").selectedOptions[0].textContent;
      this.id = ["rock", "samba", "pagode", "funk", "rap", "eletronica"];
      this.define_taxa_de_gosto();
      this.captura_elementos_escolhidos();
    }

    Musica.prototype.converte_id_em_textos = function() {
      return this.elementos_convertidos = this.elementos_escolhidos.map(function(x) {
        return x = x.replace("eletronica", "eletrônica");
      });
    };

    Musica.prototype.defini_texto = function() {
      var texto;
      switch (this.taxa_de_gosto) {
        case 0:
          texto = "curto um pouco de música";
          break;
        case 1:
          texto = "gosto de música";
          break;
        case 2:
          texto = "adoro música";
      }
      if (this.elementos_escolhidos !== 0) {
        this.converte_id_em_textos();
        return texto = texto + ", especialmente " + gerar_texto_de_itens(this.elementos_convertidos) + "";
      }
    };

    return Musica;

  })(Hobbie);

  Videogame = (function(superClass) {
    extend(Videogame, superClass);

    function Videogame() {
      this.taxa_de_gosto = document.getElementById("video_game_taxa_de_gosto").selectedOptions[0].textContent;
      this.id = ["rpg", "fps", "corrida", "jogos_de_acao", "jogos_de_aventura", "sand_box"];
      this.define_taxa_de_gosto();
      this.captura_elementos_escolhidos();
    }

    Videogame.prototype.converte_id_em_textos = function() {
      return this.elementos_convertidos = this.elementos_escolhidos.map(function(x) {
        console.log(x);
        x = x.replace("jogos_de_acao", "ação");
        x = x.replace("jogos_de_aventura", "aventura");
        return x = x.replace("sand_box", "sandbox");
      });
    };

    Videogame.prototype.defini_texto = function() {
      var texto;
      switch (this.taxa_de_gosto) {
        case 0:
          texto = "curto um game de vez enquando principalmente jogos de ";
          break;
        case 1:
          texto = "gosto de videogame, especialmente games de ";
          break;
        case 2:
          texto = "gamer fanático por jogos de ";
      }
      if (this.elementos_escolhidos !== 0) {
        this.converte_id_em_textos();
        return texto = texto + gerar_texto_de_itens(this.elementos_convertidos) + "";
      }
    };

    return Videogame;

  })(Hobbie);

  Carros = (function(superClass) {
    extend(Carros, superClass);

    function Carros() {
      this.taxa_de_gosto = document.getElementById("carros_taxa_de_gosto").selectedOptions[0].textContent;
      this.id = ["esportivos", "classicos", "corrida", "jeeps"];
      this.define_taxa_de_gosto();
      this.captura_elementos_escolhidos();
    }

    Carros.prototype.converte_id_em_textos = function() {
      return this.elementos_convertidos = this.elementos_escolhidos.map(function(x) {
        return x = x.replace("classicos", "clássicos");
      });
    };

    Carros.prototype.defini_texto = function() {
      var texto;
      switch (this.taxa_de_gosto) {
        case 0:
          texto = "curto  um pouco carros";
          break;
        case 1:
          texto = "gosto de carros";
          break;
        case 2:
          texto = "sou fanático por carros";
      }
      if (this.elementos_escolhidos !== 0) {
        this.converte_id_em_textos();
        return texto = texto + ", especialmente carros " + gerar_texto_de_itens(this.elementos_convertidos) + "";
      }
    };

    return Carros;

  })(Hobbie);

  Futebol = (function(superClass) {
    extend(Futebol, superClass);

    function Futebol() {
      this.taxa_de_gosto = document.getElementById("futebol_taxa_de_gosto").selectedOptions[0].textContent;
      this.time = document.getElementById("time").value;
      this.define_taxa_de_gosto();
    }

    Futebol.prototype.defini_texto = function() {
      var texto;
      switch (this.taxa_de_gosto) {
        case 0:
          texto = "não ligo muito, mas torço pro";
          break;
        case 1:
          texto = "sou torcedor do ";
          break;
        case 2:
          texto = "sou fanático pelo ";
      }
      if (this.elementos_escolhidos !== 0) {
        return texto = texto + this.time;
      }
    };

    return Futebol;

  })(Hobbie);

  Outros = (function(superClass) {
    extend(Outros, superClass);

    function Outros() {
      this.taxa_de_gosto = document.getElementById("outros_taxa_de_gosto" + contador.hobbie).selectedOptions[0].textContent;
      this.nome = document.getElementById("outros" + contador.hobbie).value;
      this.define_taxa_de_gosto();
    }

    Outros.prototype.defini_texto = function() {
      var texto;
      switch (this.taxa_de_gosto) {
        case 0:
          texto = "curto  um pouco ";
          break;
        case 1:
          texto = "gosto de  ";
          break;
        case 2:
          texto = "adoro ";
      }
      if (this.elementos_escolhidos !== 0) {
        return texto = texto + this.nome;
      }
    };

    return Outros;

  })(Hobbie);

  captura_nome = function() {
    return document.getElementById("nome").value;
  };

  capturar_idade = function() {
    var idade;
    idade = document.getElementById("valor_da_idade");
    if (idade !== null) {
      return idade.value;
    }
  };

  captura_profissoes = function(contador) {
    var i, j, profissao_atual, profissoes, ref;
    profissoes = [];
    for (i = j = 1, ref = contador; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      profissao_atual = document.getElementById("nome_da_profissao" + i).value;
      profissoes.push(profissao_atual);
    }
    return profissoes;
  };

  captura_religiao = function() {
    var religiao, selecao, valor;
    religiao = document.getElementById("nome_da_religiao");
    selecao = document.getElementById("praticante_ou_nao");
    valor = [];
    valor.push(religiao !== null ? religiao.value : void 0);
    valor.push(selecao !== null ? selecao.selectedOptions[0].textContent : void 0);
    return valor;
  };

  define_tipo_de_hobbie = function(hobbie) {
    switch (hobbie) {
      case "Futebol":
        return new Futebol;
      case "Cinema":
        return new Cinema;
      case "Videogame":
        return new Videogame;
      case "Música":
        return new Musica;
      case "Carros":
        return new Carros;
      case "Outros":
        return new Outros;
    }
  };

  gerar_nome = function(texto) {
    return "Meu nome é " + texto + "";
  };

  gerar_idade = function(idade) {
    return "tenho " + idade + " anos";
  };

  gerar_profissoes = function(profissoes) {
    return "sou " + gerar_texto_de_itens(profissoes);
  };

  gerar_religiao = function(religiao) {
    var texto;
    if (religiao[1] !== "Deixar em branco") {
      texto = "com relação à religião sou " + religiao[0] + " " + religiao[1] + "";
    } else {
      texto = "com relação à religião sou " + religiao[0];
    }
    return texto;
  };

  gerar_texto_de_itens = function(vetor) {
    var tamanho, texto, vetor_novo, x;
    tamanho = vetor.length;
    --tamanho;
    if (tamanho === 0) {
      return vetor[0];
    } else {
      vetor_novo = vetor.slice();
      vetor_novo.pop();
      texto = vetor_novo.join(x = ", ");
      return texto = texto + " e " + vetor[tamanho];
    }
  };

  gerar_texto = function() {
    var div, elemento, escolha, hobbies, i, idade, itens, j, k, nome, profissoes, ref, ref1, religiao, texto;
    nome = captura_nome();
    idade = capturar_idade();
    if (contador.profissao !== 0) {
      profissoes = captura_profissoes(contador.profissao);
    }
    religiao = captura_religiao();
    if (contador.hobbie !== 0) {
      hobbies = [];
      for (i = j = 1, ref = contador.hobbie; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        escolha = document.getElementById("select" + i).selectedOptions[0].textContent;
        hobbies.push(define_tipo_de_hobbie(escolha));
      }
    }
    itens = [];
    if (nome !== "") {
      itens.push(gerar_nome(nome));
    }
    if (idade !== void 0) {
      itens.push(gerar_idade(idade));
    }
    if (profissoes !== void 0) {
      itens.push(gerar_profissoes(profissoes));
    }
    if (religiao[0] !== void 0) {
      itens.push(gerar_religiao(religiao));
    }
    if (contador.hobbie !== 0) {
      for (i = k = 0, ref1 = hobbies.length - 1; 0 <= ref1 ? k <= ref1 : k >= ref1; i = 0 <= ref1 ? ++k : --k) {
        itens.push(hobbies[i].defini_texto());
      }
    }
    if (itens.length !== 0) {
      texto = gerar_texto_de_itens(itens);
    }
    div = document.getElementById("final");
    div.setAttribute("style", "visibility: visible");
    elemento = document.getElementById("texto_final");
    return elemento.textContent = texto;
  };

  botao = document.getElementById("botao_gerar_texto");

  botao.addEventListener("click", gerar_texto);

}).call(this);
